# 应用服务 WEB 访问端口

spring:
  datasource:
    url: jdbc:mysql://192.168.200.130:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: myroot
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # 指定 Mapper XML 文件的位置
  mapper-locations: classpath:mapper/*
  # 为实体类指定别名，这样在 XML 中就可以直接使用类名而不是全限定名
  type-aliases-package: com.example.mybatis_test.entity
  # (可选) 开启驼峰命名转换: user_id -> userId
  configuration:
    map-underscore-to-camel-case: true
